### PR TITLE
Another spooky update.

### LINKED ISSUE #11: ClassNotFoundException
Offending line can be found [here](https://github.com/j0ach1mmall3/KFA/blob/master/src/main/java/com/j0ach1mmall3/kfa/util/ReflectionUtil.java#L23).

When reorganising things yesterday part of me completely overlooked this blunder I made. Shall be fixing a little bit later today.

### PR DESCRIPTION
**Pull request by Fireflies**
You can now tempt your users with configurable messages that are randomly sent.
Also introduces the `#{online_player}` placeholder that is substituted for the username of a random player.

Fixes #11. 

**Warning:** could not test this build as my potato laptop™ can't handle multiple clients at once. If anyone could test I would be incredibly grateful. @j0ach1mmall3 @Saphiria

### CODE REVIEW

**Comment by j0ach1mmall3** [comment]
I approve.

**Comment by Fireflies** [comment]
It worked including restart?

**Comment by j0ach1mmall3** [comment]
It worked? What worked? What restart? .-.

**Comment by Fireflies** [comment]
>Warning: could not test this build as my potato laptop™ can't handle multiple clients at once. If anyone could test I would be incredibly grateful. @j0ach1mmall3 @Saphiria

It should automatically restart now, but I was unable to test it. :cry:

**Pull request merged**
